// Copyright 2026 OrangeCount contributors
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0

package compat

import (
	"encoding/json"
	"path/filepath"
	"strings"
	"testing"
)

// TestParityGolden is the committed-asset half of the ADR-0008 differential
// harness: it compares OrangeCount against oracle snapshots generated by
// official Beancount v3 (tools/reference/generate_golden.py). The test runs
// with pure Go; regenerating the golden files is the only step needing uv.
func TestParityGolden(t *testing.T) {
	fixtures, err := filepath.Glob(fixturePath("v3-parity", "*.bean"))
	if err != nil || len(fixtures) == 0 {
		t.Fatalf("no v3-parity fixtures: %v", err)
	}
	for _, fixture := range fixtures {
		name := strings.TrimSuffix(filepath.Base(fixture), ".bean")
		t.Run(name, func(t *testing.T) {
			golden, err := LoadGolden(fixturePath("..", "golden", "v3-parity", name+".golden.json"))
			if err != nil {
				t.Fatalf("golden snapshot unavailable: %v", err)
			}
			oc, _, err := BuildOCSide(fixture)
			if err != nil {
				t.Fatalf("orangecount evaluation failed: %v", err)
			}
			records := DiffFixture(golden.Fixture, golden, oc)
			unregistered := 0
			for _, record := range records {
				encoded, _ := json.Marshal(record)
				if record.Boundary == "" {
					unregistered++
					t.Errorf("parity difference (%s/%s): %s", record.Dimension, record.Kind, encoded)
				} else {
					t.Logf("approved boundary %s (%s/%s)", record.Boundary, record.Dimension, record.Kind)
				}
			}
			_ = unregistered
		})
	}
}

// TestParityDiffEngineGuard checks the diff helpers themselves: identical
// sides must produce no records even when orders differ.
func TestParityDiffEngineGuard(t *testing.T) {
	golden := Golden{
		Fixture: "synthetic",
		Valid:   true,
		Entries: []string{`{"a":1}`, `{"b":2}`},
		Balances: map[string]ParityBalance{
			"Assets:Cash": {Currencies: map[string]string{"USD": "1"}, Lots: nil},
		},
		Queries: map[string]json.RawMessage{
			"cash_entries": json.RawMessage(`[["2000-01-02","n"]]`),
		},
	}
	oc := OCSide{
		Valid:   true,
		Entries: []string{`{"b":2}`, `{"a":1}`},
		Balances: map[string]ParityBalance{
			"Assets:Cash": {Currencies: map[string]string{"USD": "1"}, Lots: []string{}},
		},
		Queries: map[string][][]any{"cash_entries": {{"2000-01-02", "n"}}},
	}
	if records := DiffFixture("synthetic", golden, oc); len(records) != 0 {
		encoded, _ := json.Marshal(records)
		t.Fatalf("expected clean diff, got %s", encoded)
	}
}
